require("user.options")
require("user.log")
require("user.reload")
require("user.impatient")
require("user.trouble")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")
require("user.colorscheme")
require("user.cmp")
require("user.telescope")
require("user.gitsigns")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.nvim-tree")
require("user.lualine")
require("user.project")
-- require("user.illuminate")
require("user.lsp")
require("user.guess-indent")
require("user.hop")
require("user.surround")
require("user.typescript")
require("user.toggleterm")
require("user.wilder")
require("user.indentline")
require("user.indentline")

-- require("user.windline")
-- require "user.dap"
-- require("user.rust")
-- require("user.copilot")
-- require("user.noice")
-- require("user.todo")
-- require "user.bufferline"
-- require "user.alpha"
